# Generated by Django 2.2.3 on 2019-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='c_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
